# Generated by Django 5.1 on 2024-10-07 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_remove_customer_customerid_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
