# Generated by Django 5.1 on 2024-10-19 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="slug",
        ),
    ]
