# Generated by Django 5.1 on 2024-10-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
