# Generated by Django 5.1 on 2024-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_map_image_alter_roomtype_image_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
