# Generated by Django 5.1 on 2024-10-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='hotel.coupon'),
        ),
    ]
