<<<<<<< HEAD
# Generated by Django 5.1 on 2024-11-10 03:02
=======
# Generated by Django 5.1.2 on 2024-11-07 09:27
>>>>>>> 31ff11e8338b3f14017d20e895aa84a438088467

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('hotel', '0007_remove_hotel_image'),
=======
    dependencies = [
        ("hotel", "0007_remove_hotel_image"),
>>>>>>> 31ff11e8338b3f14017d20e895aa84a438088467
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name='room',
            name='slug',
=======
            model_name="room",
            name="slug",
>>>>>>> 31ff11e8338b3f14017d20e895aa84a438088467
        ),
    ]
