# Generated by Django 5.1.2 on 2024-11-07 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0007_remove_hotel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="slug",
        ),
    ]
