# Generated by Django 5.1.2 on 2024-11-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0008_remove_room_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="check_in_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="check_out_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hotel.hotel",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="num_adults",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="num_children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hotel.roomtype",
            ),
        ),
    ]
