# Generated by Django 5.1.2 on 2024-11-17 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0010_remove_cartitem_hotel_remove_cartitem_room_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="quantity",
        ),
    ]
